[workspace]
members = [
    "compiler/curse",
    "compiler/curse_parse",
    "compiler/curse_ast",
    "compiler/curse_ast_lowering",
    "compiler/curse_hir",

    "compiler/curse_mir",

    "compiler/curse_interner",
    "compiler/curse_span",

    "compiler/curse_interpreter",
]
