[package]
name = "curse_hir"
version = "0.0.0"
edition = "2021"

[dependencies]
curse_interner = { path = "../curse_interner" }
curse_span = { path = "../curse_span" }
miette = "5.*"
thiserror = "1.*"

