[package]
name = "curse"
version = "0.1.0"
edition = "2021"

[dependencies]
curse_hir = { path = "../curse_hir" }
curse_parse = { path = "../curse_parse" }
curse_ast = { path = "../curse_ast" }
miette = { version = "5.7.0", features = ["fancy"] }
typed-arena = "2.0.2"
smallvec = "1.10.0"


