[package]
name = "curse_interpreter"
version = "0.1.0"
edition = "2021"

[dependencies]
curse_hir = { path = "../curse_hir" }
curse_interner = { path = "../curse_interner" }
curse_span = { path = "../curse_span" }
miette = "5.7.0"
thiserror = "1.0.40"
