[package]
name = "curse_parse"
version = "0.1.0"
edition = "2021"

[build-dependencies]
lalrpop = "0.19.7"

[dependencies]
lalrpop-util = "0.19.7"
curse_ast = { path = "../curse_ast" }
logos = "0.12.1"
miette = "5.6.0"
typed-arena = "2.0.2"
thiserror = "1.0.39"
